### ISSUE TITLE
Google Play 下载 APP 会卡住

### ISSUE THREAD

**Issue by gitterhit** [zk-123/shadowsocks#1]
服务器部署 shadowsocks-server，安卓看 youtube 看网页什么的都没问题，但是用 Google Play 下载 APP 会一卡一卡的，如果 APP 比较大， 一段时间后会提示下载失败。

不知道为什么，我试了很多个 java 版的 shadowsocks 服务端，基本都有这个问题，而原版的 shadowsocks 则没有这个问题。

不知道是不是 netty 相关的配置有问题 ？

**Comment by zk-123** [comment]
一会儿回去测测，它还没经过长时间考验呢，当时做它仅仅是为了学习netty，感谢反馈，一起解决它!

**Comment by zk-123** [comment]
已解决。
排查到有可能是idle时间设置太短，对客户端来说下载过程是长时间只读不写，会触发idle事件导致关闭客户端连接，已更新成默认20min。
另外对于远程连接也加上断线重连机制。

**Comment by zk-123** [comment]
补充：正在将服务改造成cli入参形式，方便部署

**Comment by gitterhit** [comment]
> 已解决。
> 排查到有可能是idle时间设置太短，对客户端来说下载过程是长时间只读不写，会触发idle事件导致关闭客户端连接，已更新成默认20min。
> 另外对于远程连接也加上断线重连机制。

大神牛逼！我刚刚测试了，Google Play 确实不会一卡一卡了。

**Comment by gitterhit** [comment]
close issue

**Comment by zk-123** [comment]
一个人维护可无聊，没人反馈自己也没什么动力，可能大部分产品都是这么堕落下去的。

**Comment by zk-123** [comment]
@gitterhit

**Comment by gitterhit** [comment]
> 一个人维护可无聊，没人反馈自己也没什么动力，可能大部分产品都是这么堕落下去的。

哈哈，你的代码已经比你原先 fork 的那个好了很多很多了，github 上面很多 java 版的 shadowsocks 我都看过，我觉得你这份项目是整个 github 里面最好的 java 版了

**Comment by zk-123** [comment]
@gitterhit 感谢夸奖，所以平时一定要养成良好的代码风格~ 😄
