### ISSUE TITLE
运行mvn package遇错

### ISSUE THREAD

**Issue by luckypoem** [zk-123/shadowsocks#2]
hi.

[root@bwg-vps shadowsocks-by-zk-123]# ls
pom.xml  README.md  shadowsocks-client  shadowsocks-common  shadowsocks-server
[root@bwg-vps shadowsocks-by-zk-123]# mvn package
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.zkdcloud:shadowsocks-server:jar:1.1.0
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ com.zkdcloud:shadowsocks:1.1.0, /root/shadowsocks-by-zk-123/pom.xml, line 81, column 21
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.zkdcloud:shadowsocks-common:jar:1.1.0
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ com.zkdcloud:shadowsocks:1.1.0, /root/shadowsocks-by-zk-123/pom.xml, line 81, column 21
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.zkdcloud:socket5-client:jar:1.1.0
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ line 23, column 21
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.zkdcloud:shadowsocks-client:pom:1.1.0
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ com.zkdcloud:shadowsocks:1.1.0, /root/shadowsocks-by-zk-123/pom.xml, line 81, column 21
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.zkdcloud:shadowsocks:pom:1.1.0
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ line 81, column 21
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] shadowsocks
[INFO] shadowsocks-common
[INFO] shadowsocks-server
[INFO] shadowsocks-client
[INFO] socket5-client
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building shadowsocks 1.1.0
[INFO] ------------------------------------------------------------------------
Downloading: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-compiler-plugin/maven-metadata.xml
[WARNING] Could not transfer metadata org.apache.maven.plugins:maven-compiler-plugin/maven-metadata.xml from/to central (http://repo.maven.apache.org/maven2): Failed to transfer file: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-compiler-plugin/maven-metadata.xml. Return code is: 501 , ReasonPhrase:HTTPS Required.
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] shadowsocks ....................................... FAILURE [0.560s]
[INFO] shadowsocks-common ................................ SKIPPED
[INFO] shadowsocks-server ................................ SKIPPED
[INFO] shadowsocks-client ................................ SKIPPED
[INFO] socket5-client .................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.799s
[INFO] Finished at: Sat Apr 18 17:17:25 CST 2020
[INFO] Final Memory: 10M/56M
[INFO] ------------------------------------------------------------------------
[ERROR] Error resolving version for plugin 'org.apache.maven.plugins:maven-compiler-plugin' from the repositories [local (/root/.m2/repository), central (http://repo.maven.apache.org/maven2)]: Plugin not found in any plugin repository -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginVersionResolutionException
[root@bwg-vps shadowsocks-by-zk-123]#

怎么解决？

**Comment by zk-123** [comment]
你好，module间有依赖，请执行：> mvn clean install

**Comment by zk-123** [comment]
@luckypoem
